language: python
python: 
    - "3.6.9"

services:
    - docker

before_install: 
    - docker build -t abautista/backend_django_api -f Dockerfile .

      #script:
      #- docker run abautista/backend_django_api coverage run --source='.' manage.py test app
