version: "3"

services:

  app:
    build:
      context: .

    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=thisPasswordNotThatSecure
    depends_on:
      - db

  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=thisPasswordNotThatSecure